In [1]:
t1 = (1, "dos", 3)
print(t1)

(1, 'dos', 3)


In [2]:
t2 = (t1, "cuatro")
print(t2)

((1, 'dos', 3), 'cuatro')


In [3]:
t1 = (1, "dos", 3)
t2 = (t1, "cuatro")

In [4]:
print(t1+t2)

(1, 'dos', 3, (1, 'dos', 3), 'cuatro')


In [6]:
print((t1+t2)[3])

(1, 'dos', 3)


In [8]:
print((t1+t2)[2:5])

(3, (1, 'dos', 3), 'cuatro')


In [9]:
t3 = ("cinco",) #t3 es una tupla de un solo elemento
print(t1+t2+t3)

(1, 'dos', 3, (1, 'dos', 3), 'cuatro', 'cinco')


In [11]:
tup1 = (5)
print(tup1)

5


In [12]:
type(tup1)

int

In [13]:
tup2 = (5,)
print(tup2)

(5,)


In [14]:
type(tup2)

tuple

In [16]:
x = (1, 2, (3, "juan", 4), "Hola")

In [17]:
#1
x[0]

1

In [18]:
#(3, 'juan', 4)
x[2]

(3, 'juan', 4)

In [19]:
#'Hola'
x[-1]

'Hola'

In [20]:
#4
x[2][2]

4

In [21]:
#4
x[2][-1]

4

In [22]:
#'a'
x[-1][-1]

'a'

In [23]:
#'l'
x[-1][2]

'l'

In [24]:
#(1,)
x[0:1]

(1,)

In [25]:
#(1, 2, (3, 'juan', 4))
x[0:-1]

(1, 2, (3, 'juan', 4))

In [26]:
#4
len(x)

4

In [27]:
#True
2 in x

True

In [28]:
#False
3 in x

False

In [29]:
#error
x[0] = 8

TypeError: 'tuple' object does not support item assignment

In [49]:
techs = ["MIT", "Cal Tech"]
ivis = ["Harvard", "Yale", "Brown"]

In [50]:
ivis[1]

'Yale'

In [51]:
univs = [techs, ivis]
univs1 = [["MIT", "Cal Tech"], ["Harvard", "Yale", "Brown"]]

In [52]:
print(univs)

[['MIT', 'Cal Tech'], ['Harvard', 'Yale', 'Brown']]


In [53]:
print(univs1)

[['MIT', 'Cal Tech'], ['Harvard', 'Yale', 'Brown']]


In [54]:
techs.append("RPI")

In [55]:
print(univs1)

[['MIT', 'Cal Tech'], ['Harvard', 'Yale', 'Brown']]


In [56]:
print(univs)

[['MIT', 'Cal Tech', 'RPI'], ['Harvard', 'Yale', 'Brown']]


In [57]:
techs[2] = "WPI"

In [58]:
techs

['MIT', 'Cal Tech', 'WPI']

In [59]:
x = [1, 2, [3, "juan", 4], "Hola"]

In [60]:
#1
x[0]

1

In [61]:
#[3, 'juan', 4]
x[2]

[3, 'juan', 4]

In [63]:
#'Hola'
x[-1]

'Hola'

In [64]:
#4
x[2][2]

4

In [65]:
#4
x[2][-1]

4

In [66]:
#'a'
x[-1][-1]

'a'

In [67]:
#'l'
x[-1][2]

'l'

In [68]:
#[1]
x[0:1]

[1]

In [69]:
#[1, 2, [3, 'juan', 4]]
x[0:-1]

[1, 2, [3, 'juan', 4]]

In [70]:
#4
len(x)

4

In [71]:
#True
2 in x

True

In [72]:
#False
3 in x

False

In [73]:
#error
x[0] = 8

In [74]:
#[8, 2, [3, 'juan', 4], 'Hola']
x

[8, 2, [3, 'juan', 4], 'Hola']

In [75]:
import numpy as np

In [76]:
arreglo1 = np.arange(5)

In [77]:
arreglo1

array([0, 1, 2, 3, 4])

In [78]:
np.full((4,2), True, dtype=bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [79]:
np.ones((4,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.ones((4,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [82]:
np.random.random((2,2))

array([[0.99365339, 0.72712424],
       [0.77275851, 0.80629865]])

In [83]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
arreglo1[1]

1

In [85]:
arreglo1[-1]

4

In [86]:
A = np.array([0, 1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10, 11])
C = np.add(A, B)

In [87]:
C

array([ 6,  8, 10, 12, 14, 16])

In [90]:
B = np.array([6, 7, 8, 9, 10, 11])
C = np.add(B, 3)

In [91]:
C

array([ 9, 10, 11, 12, 13, 14])

In [92]:
arreglo3 = np.arange(10)

In [93]:
arreglo3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arreglo3[1:7:2]

array([1, 3, 5])